sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

rust:
  - 1.7.0
  - nightly
  - beta
  - stable

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - if [[ "$TRAVIS_RUST_VERSION" == "1.7.0" ]]; then travis-cargo test -- --features legacy ; fi
  - if [[ "$TRAVIS_RUST_VERSION" != "1.7.0" ]]; then travis-cargo test ; fi
#after_success:
  #- travis-cargo coveralls --no-sudo --verify

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
